### ISSUE TITLE
Entitylerin Tasarlanması, Diagram Çizimi

### ISSUE THREAD

**Issue by moaydogdu** [moaydogdu/StockManagementStudyCase#1]
Proje içerisinde ihtiyaç duyulan enttity nesnelerinin tasarlanması, "Class" ve "ER (Entity Relationship)" diyagramlarının çizilmesi gerekmektedir.

**Comment by mehmetseymusyuzen** [comment]
![class-diagram](https://github.com/moaydogdu/StockManagementStudyCase/assets/76790253/bc89c7e8-f123-40e9-aa83-4d31d3c11e50)

![diagrams](https://github.com/moaydogdu/StockManagementStudyCase/assets/76790253/31982f7d-6d4a-4b19-b8c8-982d489f8ef8)

**Comment by artfulCoder98** [comment]
:_)
