### ISSUE TITLE
Stock satış sürecinin kodlanması.

### ISSUE THREAD

**Issue by moaydogdu** [moaydogdu/StockManagementStudyCase#39]
Bu süreçte bir stoğu ve hangi depodan bu stoğun çıkış yapacağını belirten bir istek alınmalı.

Sonrasında ilgili depoda bu stoğun yeterli miktarda olup olmadığı kontrol edilmeli.

Devam eden süreçte ilgili WareHouseStock güncellenmeli (satış miktarı düşülmeli), bir stockTransaction oluşturulmalı, eğer bu işlem geçmiş tarihli ise, sonrasında kalan StockTransactionların da JPQL kullanılarak güncellenmesi gerekiyor.

**Comment by artfulCoder98** [comment]
bunu deniyorum
