### ISSUE TITLE
 StockTransactionType ve UnitType Enumlarının Kodlanması

### ISSUE THREAD

**Issue by mehmetseymusyuzen** [moaydogdu/StockManagementStudyCase#5]
StockTransactionType ve UnitType Enumlarinin Kodlanmasi ve Ilgili Entity Nesneleriyle Iliskilendirilmesi.

**Comment by moaydogdu** [comment]
Ayrıca bu enum nesnelerinin liqubase tarafına eklenmesi gerekmektedir.
